### PR TITLE
Improve performance of revcomp algorithme

### PR DESCRIPTION
**Pull request by natir**
Hello,

Description of change :
- Replace function by a functor
- this functor use a C table for nucleotide complement (just pointer arithmetic operation)
- for reverse use a modification of std::reverse of gnu library (complexity O(n/2) not 0(n))

Benefit :
- Less compute time

out
actual version : "switch_transform" 
my version : "tabular_revert"

Disadvantage :
- A little bit of memory usage
- Use a class in place of function
- We need use std::string in place of const std::string in functor call

I have create a [little project](https://github.com/natir/better_rev_comp) to test my hypothesis, and generate attach file (run information is in README.md of this project).

Thanks for your work.

### CODE REVIEW

**Comment by pimentel** [comment]
@natir thanks for this! we will be testing it in the coming weeks (we have a number of benchmarks that we run internally on every version before it goes out). I will keep you posted of our progress.

Best,

Harold

**Comment by natir** [comment]
Ok great !

If you want integrate my algorithme, maybe i can make a little modification, for more code quality : 

* transform revcomp class into singleton, just one class creation in all execution [see my project](https://github.com/natir/better_rev_comp) for test code
* better naming for class

Best

Natir

**Comment by ajo2995** [comment]
If you pass the string by reference the performance of switch_transform matches the performance of tabular_revert.
`std::string switch_transform_const_ref(std::string const & seq)`
time

**Comment by natir** [comment]
I update the [better_rev_comp](https://github.com/natir/better_rev_comp) project with const_ref and ref version of algorithms. I get this result (reproduce on another computer with clang++ and g++) : 

out

This is a very little optimisation, they save very little bit of time, but the change in code isn't trivial, I can understand you prefer use const ref version of switch transform.

**Pull request closed without merging**
