### PR TITLE
Fix typo in help text

### PR DESCRIPTION
**Pull request by chrisamiller**

### CODE REVIEW

**Comment by mschilli87** [comment]
@pmelsted, @pimentel: Is kallisto still being actively maintained? It's kind of a bad sign if a simple typo fix PR is not merged after four months. There is [another one](https://github.com/pachterlab/kallisto/pull/109#issue-70061525) open for more than 1.5 years(!). I think this really discourages contributions. Also the list of open issues without any repsonse by a developer keeps growing and reached a point where I would hesitate to download and try it but rather look for an alternative coming in as a potential new user. Following this project since the pre-print, I know it works for me and I'll keep using it as long as nothing breaks. But once it does, I'd rather find some maintained rip-off instead of spending time to fix it and never getting it merge. Would be a pity to see this go eventually. Anything the community could do to help? And thank you for the work you put in this so far.

**Comment by lakigigar** [comment]
Hi Marcel, 

Thanks for your comment. You're right that we ought to have fixed this typo and apologize for not doing so earlier. To answer your question we are still working on kallisto, strive to fix issues when they arise, and have made improvements. You can see a list of changes on the release notes here: https://pachterlab.github.io/kallisto/download
Version 0.43.1 fixed a bug related to quantification but generally we've also chosen not to make too many releases as we are trying to keep the program stable. One thing you'll see is that both the kallisto pseudoalignments and the quantification has not changed much since the initial release, and we see this as a feature rather than a bug. More recently, we've added a command to kallisto (in version 0.45.0) that produces BUS format, which is useful for single-cell RNA-seq processing. 

In terms of answering questions right away, and addressing issues such as the typo fix, unfortunately we cannot always be responsive because there is no one dedicated to that work on the project. This is not for lack of trying; sadly funding of bioinformatics projects such as kallisto are difficult to obtain and we have been unsuccessful despite repeated attempts. We are hopeful that our latest proposal, which includes a component directly for funding support of kallisto, will be funded given the large number of users at this point. Until that happens, the maintenance must happen on time that is carved out of other projects we are all primarily funded to work on. It would be great if you, or others, wanted to jump in to help and we'd be happy to work out a good mechanism for management. 

Thanks again,
Lior

**Comment by chrisamiller** [comment]
Just to be clear, the above commenter's notes do not represent my views. I have several software packages that get updated more infrequently than they should, so I get it. Looking forward to the new release - best of luck!

**Comment by mschilli87** [comment]
@chrisamiller: Sorry for hijacking you PR to bring this up. Maybe a separate issue would have been better. I did not mean to complain or step on any toes. I just wanted to know what's the state and if I see myself in a situation where I can actually improve the situation, I'll happily contact @lakigigar now that I know it would be appreciated. :smiley:

**Comment by Yenaled** [comment]
Closing this; typo no longer exists in more recent versions

**Pull request closed without merging**
